# Generated by Django 4.1 on 2022-08-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('branch_id', models.IntegerField(db_column='branch_id', primary_key=True, serialize=False)),
                ('branch_number', models.IntegerField(db_column='branch_number')),
                ('branch_name', models.CharField(db_column='branch_name', max_length=200)),
                ('branch_address_id', models.IntegerField(db_column='branch_address_id')),
            ],
        ),
    ]
