# Generated by Django 4.1 on 2022-08-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('iban', models.TextField()),
            ],
            options={
                'db_table': 'cuenta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('mov_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_id', models.IntegerField(blank=True, null=True)),
                ('mov_total', models.IntegerField(blank=True, null=True)),
                ('mov_type', models.TextField(blank=True, null=True)),
                ('mov_datetime', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movimientos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCuentas',
            fields=[
                ('tipoid', models.AutoField(db_column='TipoId', primary_key=True, serialize=False)),
                ('tipo', models.TextField(db_column='Tipo')),
            ],
            options={
                'db_table': 'tipo_cuentas',
                'managed': False,
            },
        ),
    ]
