# Generated by Django 4.1 on 2022-08-14 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuenta',
            options={},
        ),
        migrations.AlterModelOptions(
            name='movimientos',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tipocuentas',
            options={},
        ),
    ]
