# Generated by Django 4.1 on 2022-08-14 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0002_alter_cuenta_options_alter_movimientos_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='typeid',
            field=models.ForeignKey(blank=True, db_column='typeId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Cuentas.tipocuentas'),
        ),
    ]
