# Generated by Django 4.1 on 2022-08-14 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tipoclientes',
            options={},
        ),
    ]
