# Generated by Django 4.1 on 2022-08-14 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_alter_cliente_options_alter_empleado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Clientes.tipoclientes'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='branch_id',
            field=models.IntegerField(default=79),
        ),
    ]
