# Generated by Django 4.1 on 2022-08-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0003_cliente_tipo_alter_cliente_branch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='branch_id',
            field=models.IntegerField(default=58),
        ),
    ]
