# Generated by Django 4.1 on 2022-08-14 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0012_cliente_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='tipo',
        ),
    ]
