# Generated by Django 4.1 on 2022-08-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarcasTarjetas',
            fields=[
                ('marcaid', models.AutoField(db_column='MarcaId', primary_key=True, serialize=False)),
                ('marca', models.TextField(db_column='Marca')),
            ],
            options={
                'db_table': 'marcas_tarjetas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarjetas',
            fields=[
                ('tarjetaid', models.AutoField(db_column='TarjetaId', primary_key=True, serialize=False)),
                ('numero', models.IntegerField(db_column='Numero')),
                ('cvv', models.IntegerField(db_column='CVV')),
                ('fechaotorgamiento', models.TextField(db_column='FechaOtorgamiento')),
                ('fechaexpiracion', models.TextField(db_column='FechaExpiracion')),
                ('tipo', models.TextField(db_column='Tipo')),
            ],
            options={
                'db_table': 'tarjetas',
                'managed': False,
            },
        ),
    ]
