# Generated by Django 4.1 on 2022-08-14 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tarjetas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marcastarjetas',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tarjetas',
            options={},
        ),
    ]
