# Generated by Django 4.1 on 2022-08-14 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0013_remove_cliente_tipo'),
        ('Tarjetas', '0002_alter_marcastarjetas_options_alter_tarjetas_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjetas',
            name='customerid',
            field=models.ForeignKey(db_column='CustomerId', default=23, on_delete=django.db.models.deletion.DO_NOTHING, to='Clientes.cliente'),
        ),
        migrations.AddField(
            model_name='tarjetas',
            name='marcaid',
            field=models.ForeignKey(db_column='MarcaId', default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='Tarjetas.marcastarjetas'),
        ),
    ]
