# Generated by Django 4.1 on 2022-08-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_type', models.TextField()),
                ('loan_date', models.TextField()),
                ('loan_total', models.IntegerField(default='2022-08-14')),
                ('customer_id', models.IntegerField()),
            ],
            options={
                'db_table': 'prestamo',
            },
        ),
    ]
