# Generated by Django 4.1 on 2022-08-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0002_alter_prestamo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='loan_total',
            field=models.IntegerField(default='2022-08-14'),
        ),
    ]
